import './globals.css'
import bodyImgUrl from '../../public/inflicted.png'
export const metadata = {
  title: 'Biographical-notes'
  // description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className=""
        style={{ background: `#333 url('${bodyImgUrl.src}') repeat` }}
      >
        {children}
      </body>
    </html>
  )
}
